stages:
    - build

format-check:
    stage: build
    image: node:17-alpine3.14
    script:
        - echo "Formatting code"
        - npx prettier . --write

build-image:
    image: docker:19.03.12
    stage: build
    services:
        - docker:19.03.12-dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY/m7093/system-design-capstone/sdc-reactapp:latest ./frontend
        - docker build -t $CI_REGISTRY/m7093/system-design-capstone/sdc-restapi:latest ./restapi
        - docker push $CI_REGISTRY/m7093/system-design-capstone/sdc-restapi:latest
        - docker push $CI_REGISTRY/m7093/system-design-capstone/sdc-reactapp:latest
    only:
        - main
