stages:
    - build
    - deploy

format-check:
    stage: build
    image: node:17-alpine3.14
    script:
        - echo "Formatting code"
        - npx prettier . --check

build-image:
    image: docker:19.03.12
    stage: deploy
    environment:
      name: prod
      url: http://174.138.41.154
    services:
        - docker:19.03.12-dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY/m7093/system-design-capstone/sdc-frontend:prod ./frontend
        - docker build -t $CI_REGISTRY/m7093/system-design-capstone/sdc-restapi:prod ./restapi
        - docker push $CI_REGISTRY/m7093/system-design-capstone/sdc-frontend:prod
        - docker push $CI_REGISTRY/m7093/system-design-capstone/sdc-restapi:prod
