version: "3.8"
services:
  frontend:
    image: registry.gitlab.com/m7093/system-design-capstone/sdc-frontend:prod
    ports:
      - 80:80

  restapi:
    image: registry.gitlab.com/m7093/system-design-capstone/sdc-restapi:prod
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
