services:
    postgres:
        image: postgres:14.2-alpine
        environment:
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=sdc
        ports:
            - 5432:5432
        container_name: postgres
        restart: on-failure
    frontend:
        image: sdc-frontend
        build: ./frontend
        volumes:
            - ./frontend:/app
        ports:
            - 3000:3000
        container_name: sdc-frontend
    restapi:
        image: sdc-restapi
        build: ./restapi
        volumes:
            - ./restapi:/app
        ports:
            - 3001:3001
        container_name: sdc-restapi
        environment:
            - DATABASE_URL=postgres://postgres:test@postgres:5432/sdc
        depends_on:
            - postgres
