services:
    postgres:
        image: postgres:14.2-alpine
        environment:
            - POSTGRES_PASSWORD=test
            - POSTGRES_USER=app
            - POSTGRES_DB=sdc
        ports:
            - 5435:5432
        container_name: postgres
        restart: on-failure
    frontend:
        image: sdc-frontend
        build:
            context: ./frontend
            target: dev
        environment:
            - REACT_APP_API_BASE_URL=http://localhost:3001
        volumes:
            - ./frontend:/app
        ports:
            - 3000:3000
        container_name: sdc-frontend
    restapi:
        image: sdc-restapi
        build:
            context: ./restapi
            target: dev
        volumes:
            - ./restapi:/app
        ports:
            - 3001:3001
        container_name: sdc-restapi
        environment:
            - DATABASE_URL=postgres://app:test@postgres:5432/sdc
        depends_on:
            - postgres
